### ISSUE TITLE
java.lang.RuntimeException: Main-class has no main method!

### ISSUE THREAD

**Issue by weiminn** [serval-snt-uni-lu/DroidRA#4]
On most of the APKs, init(...) method in the main() method of the DroidRA source code could successfully generate the DummyMainClass along with its dummy main() method. However, when reflectionAnalysis() method runs, DummyMainClass mysteriously disappears from the Scene.v(), showing the following error message:

![main-class error](https://user-images.githubusercontent.com/22119662/60974680-13bdc280-a35d-11e9-8a85-2a59ce8b8db6.png)

Using the same DroidRA source code, I could successfully instrument and create boosted versions of a very small minority of the APKs in my dataset. With those APKs, I could observe, using breakpoints, that the DummyMainClass do not disappear when the reflectionAnalysis() method runs. However, I believe that something - possibly a tweak in options or some arguments - could be done to make it work more consistently.

Is there any special options/arguments in DroidRA that I could explore or is there any necessary updates needed to be made to the source code to analyze latest APKs since it has been a handful of years since the source code was last updated?

**Comment by weiminn** [comment]
I found the error that is causing the problem. The main class is not generated for some of the APKs because when soot is writing the output, it faces this error (depicted below) which causes soot to end abruptly without having generated the `dummyMainClass` and move onto with the analysis phase.

```
Exception in thread "main" java.lang.RuntimeException: Failed to convert <android.app.Activity: void <clinit>()>
	at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:2039)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:402)
	at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.processNewMethod(OnFlyCallGraphBuilder.java:755)
	at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.processReachables(OnFlyCallGraphBuilder.java:269)
	at soot.jimple.spark.solver.OnFlyCallGraph.build(OnFlyCallGraph.java:83)
	at soot.jimple.spark.builder.ContextInsensitiveBuilder.build(ContextInsensitiveBuilder.java:100)
	at soot.jimple.spark.SparkTransformer.internalTransform(SparkTransformer.java:101)
	at soot.SceneTransformer.transform(SceneTransformer.java:36)
	at soot.Transform.apply(Transform.java:102)
	at soot.RadioScenePack.internalApply(RadioScenePack.java:68)
	at soot.jimple.toolkits.callgraph.CallGraphPack.internalApply(CallGraphPack.java:58)
	at soot.Pack.apply(Pack.java:117)
	at soot.PackManager.runWholeProgramPacks(PackManager.java:611)
	at soot.PackManager.runPacksNormally(PackManager.java:495)
	at soot.PackManager.runPacks(PackManager.java:419)
	at edu.psu.cse.siis.coal.Analysis.performAnalysis(Analysis.java:68)
```
It seems to be having some problems with some conversion operation in `soot.asm` package.

**Comment by BedoMagdi** [comment]
I'm having the same problem. If someone has found a solution, please share it with us. Thanks!

**Comment by Mech0n** [comment]
may by too late. I try to replace the process of constructing dummy main, and use FlowDroid to make ICFG, and solved this problem.
